baseurl = "https://mitchbeebe.com/"
languageCode = "en-US"
title = "Mitch Beebe"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain-vitae"
ignoreFiles = ["\\*.Rmd$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Mitch Beebe"
  description = "My personal website and blog"
  resume = "MBeebeResume-2019-04-06.pdf"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "mitchbeebe"
  Email         = "beebe.mitch@gmail.com"
  LinkedIn      = "mitchbeebe"

[params.vitae]
  website = "mitchbeebe.com"
  website_full = "https://mitchbeebe.com/"
  city = "New York, NY"

## Main Menu
[[menu.main]]
  name = "posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 200
  url = "/vitae/"
